/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : CRC32
 #	author : miyako
 #	2014/11/23
 #
 # --------------------------------------------------------------------------------*/



// --- CRC32
void CRC32_Get(sLONG_PTR *pResult, PackagePtr pParams);
